Big-Bytez/cse110-fa21-group19

source/demos/LocalStorageDemo.html
source/demos/LocalStorageDemo.js

Demonstration of Capabilities of Local Storage 
- Everything in Local Storage is indexed by key ( name of recipe) then stores other attributes as JSON 
- ( if we decide to go with grocery list this will get more complicated will maybe use key as favorite recipes and key as grocery list and then store all other attributes as a JSON but will have to refractor the JSON )
- One can create custom functions in order to sort the Local Storage : Demo shows the ability to do it by time
- Users should have the ability to delete everything from their local storage: localStorage.clear()
-  Can Sort Local Storage by time or Alphabetically 
- Proposal: Should recently viewed should be stored in Session storage; or once again can maintain two lists in Local Storage? ( I think the second one is better …

Created A Demo for Local Storage

---

source/home-page/assets/script.js
source/home-page/index.html
source/search_page/index.html

4. Create PR
The searchbar for the home page now redirects after submission, however the data hasn't been rendered in yet, which will be the next step.  Some routing fixings as well for other pages.
Tried submitting from the search bar on home page leads to rerouting to search page

Searchbar routing basic, no data rendering yet

---

source/components/RecipeTile.css
source/home-page/assets/script.js
source/home-page/index.html
source/home-page/styles/style.css

4. Create PR
Fixed codacy errors from previous pull requests and made new feed slider free.
I inserted dummy recipe cards into the container divs

Home page nick

---

source/user-portal/styles/style.css

4. Create PR
Changed color scheme, fonts, added shuffle button, removed ability to change user photo, edited nav bar styling
This code is working in the user-portal repository

edited user page styling 

---

source/user-portal/index.html

4. Create PR
Changed color scheme, fonts, added shuffle button, removed ability to change user photo, edited nav bar styling
This code is working in the user-portal repository

edited user page styling

---

source/home-page/assets/script.js
source/home-page/styles/style.css

4. Create PR
Fixed bug by commenting out unused code

fixed bug introduced by merge

---

source/home-page/index.html
source/home-page/styles/style.css

4. Create PR
removed side nav and reinstated top button positions
Tested locally

Home-page-mvp

---

source/search_page/index.html
source/search_page/styles/style.css

Removed nav-bar and 'page'. i'll fix the clickableness of the recipe tiles in a different commit.
4. Create PR

prepared search-page for mvp

---

source/user-portal/assets/favRecipe.js
source/user-portal/assets/script.js
source/user-portal/styles/style.css

4. Create PR
- Added some more CSS code for resizing issues
- Added JS functions to call local storage information
- Temporary function in place to parse data for a set recipe
- **Added a function from Lab 6, need confirmation if we can use that**
- Used a recipe example to test the local storage functions
- Resized locally
- Birthday cake image is grabbed from local storage, rather than saved or original json.

added functions for local storage

---

source/home-page/assets/script.js
source/home-page/index.html
source/home-page/styles/style.css

4. Create PR
Got Thumbnails to show up on home page
Tested Locally

got home thumbnails to work with Peder's template

---

source/home-page/index.html
source/home-page/styles/style.css
source/recipe-individual/index.html
source/search_page/index.html

4. Create PR
Made home page not have so much sliding room so no overlapping elements. 
Hid nav bar and removed shuffle button.
Resized screen and made sure it looks good on diff screen sizes.

Css changes

---

source/home-page/assets/script.js
source/home-page/styles/style.css

4. Create PR
The merge introduced a bug on home page I fixed it by uncommenting out some code

fixed bug introduced by merge on the home page

---

source/home-page/assets/script.js
source/recipe-individual/index.html
source/recipe-individual/scripts/individual.js
source/recipe-individual/scripts/individualCustom.js
source/user-portal/assets/favRecipe.js
source/user-portal/assets/script.js
source/user-portal/index.html

4. Create PR
Integrated the Spoonacular Call with Individual Page, reworked the individual page into a shadow dom
Tested Locally

integrated backend api

---

source/home-page/styles/style.css
source/recipe-individual/scripts/individual.js
source/search_page/assets/script.js
source/search_page/index.html
source/user-portal/index.html

4. Create PR
I corrected the file path for the image and changed css to make user portal appear in top right instead of overlapping w searchbar.
I checked locally.

Fixed user portal button and made image appear

---

source/home-page/assets/script.js
source/recipe-individual/scripts/individual.js
source/search_page/assets/script.js

chenged the api key from Liza's to Brian's

---

admin/meetings/11221-Teammeeting.md
source/home-page/assets/script.js
source/recipe-individual/scripts/individual.js
source/search_page/assets/script.js
source/user-portal/scripts/upload.js

4. Create PR
Updated API keys
Checked locally

Update API keys

---

source/home-page/assets/script.js
source/home-page/index.html
source/recipe-individual/scripts/individual.js
source/search_page/assets/script.js
source/search_page/assets/searchRecipe.js

4. Create PR
Added the school api created by Nicholas 5,000 requests

School api

---

source/components/CSS/thumbnail.css
source/components/RecipeTile.css
source/components/RecipleTile.html
source/components/SearchBar.html
source/home-page/assets/script.js
source/home-page/index.html
source/home-page/styles/style.css
source/recipe-individual/index.html
source/recipe-individual/individual.css
source/recipe-individual/scripts/individualCustom.js
source/search_page/assets/searchRecipe.js
source/search_page/mini-recipe.html
source/search_page/styles/style.css
source/user-portal/index.html
source/user-portal/styles/style.css

4. Create PR
(I pulled one hour ago so branch is up-to-date)
I made the user portal and the search page functional on mobile devices
i tested in dev tools locally

made user portal and search page mobile

---

source/recipe-individual/individual.css
source/recipe-individual/scripts/individualCustom.js

4. Create PR
Added Snackbar notification
Tested locally.

Finished Adding Snackbar Notifications

---

source/user-portal/assets/script.js
source/user-portal/index.html
source/user-portal/styles/style.css

4. Create PR
added time filter on the user portal

added time filter

---

source/home-page/assets/script.js
source/home-page/index.html
source/recipe-individual/index.html
source/recipe-individual/scripts/individual.js
source/search_page/assets/script.js
source/search_page/index.html
source/user-portal/scripts/upload.js

4. Create PR
Added shuffle buttons to home, individual and search-page. CSS isn't perfect, but will sort that out later.

Shuffle button implementation

---

source/user-portal/index.html
source/user-portal/styles/style.css

4. Create PR
change filter a little bit to fit mobile device

add mobile support

---

source/user-portal/assets/script.js
source/user-portal/index.html

4. Create PR
added search feature on fav recipes.

added search fav recipe feacture

---

source/home-page/styles/style.css
source/recipe-individual/individual.css
source/recipe-individual/scripts/individualCustom.js
source/search_page/styles/style.css
source/user-portal/styles/style.css

4. Create PR
I made the title font size more uniform page-to-page. removed home-page browsing feature from mobile version, edited recipe page mobile styling, and other small mobile changes, additionally I deleted some unused, old, commented out code. More minor edits to come.
Tested locally

edited mobile styling

---

source/home-page/index.html
source/home-page/styles/style.css
source/recipe-individual/index.html
source/recipe-individual/individual.css
source/search_page/index.html
source/search_page/styles/style.css
source/user-portal/index.html
source/user-portal/styles/style.css

4. Create PR
- Added text to user-logo & Shuffle
- fixed formating between the different pages. Now logos should be placed the same place and have the same formating when you move through the site. 
- Made some changes to the big bytez logo formating
-

Adding text, fixing formatting

---

source/home-page/assets/script.js
source/search_page/assets/script.js
source/test/E2E.test.js
source/user-portal/assets/script.js

4. Create PR
deleted unused functions and comments

deleted unused functions and comments

---

source/search_page/assets/script.js

4. Create PR
added what happens if search finds no results
Tested locally

added what happens if search finds no results
